spring:
  cloud:
    gateway:
      enabled: true  #开启网关
      discovery:
        locator:
          enabled: true #开启自动路由,以服务id建立路由，服务id默认大写
          lower-case-service-id: true #服务id设置为小写
eureka:
  client:
    service-url:
      defaultZone: http://192.168.73.110:8200/eureka/